# Generated by Django 4.1 on 2022-08-16 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('cc', models.CharField(help_text='uniquely identifies countries', max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'countries',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.IntegerField(help_text='uniquely identifies leagues within a country', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.country')),
            ],
            options={
                'db_table': 'leagues',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fh', models.SmallIntegerField()),
                ('sh', models.SmallIntegerField()),
                ('ft', models.SmallIntegerField()),
                ('o1', models.SmallIntegerField()),
                ('o2', models.SmallIntegerField()),
                ('ot', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'predictions',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fh', models.SmallIntegerField()),
                ('sh', models.SmallIntegerField()),
                ('ft', models.SmallIntegerField()),
                ('o1', models.SmallIntegerField()),
                ('o2', models.SmallIntegerField()),
                ('ot', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'results',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=255, unique_for_date='date')),
                ('fixture', models.IntegerField()),
                ('home', models.CharField(max_length=60)),
                ('away', models.CharField(max_length=60)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.league')),
                ('predictions', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='matches.prediction')),
                ('results', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='matches.result')),
            ],
        ),
    ]
