# Generated by Django 4.1 on 2022-08-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_alter_match_predictions_alter_match_results'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='slug',
        ),
        migrations.AddField(
            model_name='match',
            name='motd',
            field=models.BooleanField(default=False),
        ),
    ]
