# Generated by Django 4.1 on 2022-09-19 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0007_match_postponed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="match",
            old_name="motd",
            new_name="hot_pick",
        ),
        migrations.AddField(
            model_name="match",
            name="country",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="matches.country",
            ),
        ),
    ]
